//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParallelTypeSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersFiles
    {
        public int Id { get; set; }
        public int FileId { get; set; }
        public int UserId { get; set; }
        public int PermissionTypeId { get; set; }
    
        public virtual Files Files { get; set; }
        public virtual PermissionTypes PermissionTypes { get; set; }
        public virtual Users Users { get; set; }
    }
}
